# Site Settings
title: My Resume
url: 'http://webjeda.com'
description: A beautiful Jekyll theme for creating resume

# Theme Settings
theme_skin: blue

# Layout Settings
source: ./site
destination: ./target

data_dir: _configs
includes_dir: _includes
layouts_dir: _layouts

sass:
  sass_dir: _themes

# Build settings
encoding: 'utf-8'

# Development Settings
port: 3000
host: 127.0.0.1
safe: true
